// This file was generated by Cloud Code Bindings Generator. Modifications will be lost upon regeneration.
using System.Collections.Generic;
using System.Threading.Tasks;
using System;

namespace Unity.Services.CloudCode.GeneratedBindings
{
    public class PlayerDataServiceBindings
    {
        readonly ICloudCodeService k_Service;
        public PlayerDataServiceBindings(ICloudCodeService service)
        {
            k_Service = service;
        }

        public async Task<string> SavePlayerName(string NewName)
        {
            return await k_Service.CallModuleEndpointAsync<string>(
                "UnitySignInIntegrationCloud",
                "SavePlayerName",
                new Dictionary<string, object>()
                {
                    {"NewName", NewName},
                });
        }

        public async Task<string> GetPlayerName()
        {
            return await k_Service.CallModuleEndpointAsync<string>(
                "UnitySignInIntegrationCloud",
                "GetPlayerName",
                new Dictionary<string, object>()
                {
                });
        }

        public async Task<string> SaveCoin(int Coin)
        {
            return await k_Service.CallModuleEndpointAsync<string>(
                "UnitySignInIntegrationCloud",
                "SaveCoin",
                new Dictionary<string, object>()
                {
                    {"Coin", Coin},
                });
        }

        public async Task<int> GetCoin()
        {
            return await k_Service.CallModuleEndpointAsync<int>(
                "UnitySignInIntegrationCloud",
                "GetCoin",
                new Dictionary<string, object>()
                {
                });
        }
    }
}
